AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A SAM template for deploying multiple Lambda functions.
Resources:
  eventsGet:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: exodb-eventsGetFunc
      Handler: eventsGet.handler
      Runtime: nodejs20.x
      CodeUri: s3://exodblambdafunctions/7948a9b4ff83abb66893d1d0c0bc4b69
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud
    Metadata:
      SamResourceId: eventsGet
  eventIdGetPost:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: exodb-eventIdGetPostFunc
      Handler: eventIdGetPost.handler
      Runtime: nodejs20.x
      CodeUri: s3://exodblambdafunctions/f94e1a03fa77ee3611756b00fb5f998e
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud
    Metadata:
      SamResourceId: eventIdGetPost
  divisionsGet:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: exodb-eventDivisionsGetFunc
      Handler: divisionsGet.handler
      Runtime: nodejs20.x
      CodeUri: s3://exodblambdafunctions/4654894c5290a63ca5f4d52a18eb12d3
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud
    Metadata:
      SamResourceId: divisionsGet
  divIdGet:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: exodb-eventDivIdGetFunc
      Handler: divIdGet.handler
      Runtime: nodejs20.x
      CodeUri: s3://exodblambdafunctions/51e6cbead175d7a89465b3f6dcbf0ab8
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud
    Metadata:
      SamResourceId: divIdGet
  auditOngoing:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: exodb-eventsAuditOngoing
      Handler: auditOngoing.handler
      Runtime: python3.10
      CodeUri: s3://exodblambdafunctions/90808ea0b32500fd98ddde324993b28b
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud
    Metadata:
      SamResourceId: auditOngoing
  updateTeamFromStream:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: exodb-updateTeamFromStream
      Handler: updateTeamFromStream.handler
      Runtime: python3.10
      CodeUri: s3://exodblambdafunctions/c5ffe540ddec60cad976d65f1997c5a3
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud
    Metadata:
      SamResourceId: updateTeamFromStream
  updateFutureEventsDataProcessor:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: exodb-eventsFutureUpdateFuncDataProcessor
      Handler: updateFutureEventsDataProcessor.handler
      Runtime: python3.10
      CodeUri: s3://exodblambdafunctions/41046464184a526f7e847f9e3786eab6
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud
    Metadata:
      SamResourceId: updateFutureEventsDataProcessor
  updateOngoingAttributeFunc:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: exodb-eventsUpdateOngoingAttribute
      Handler: updateOngoingAttribute.handler
      Runtime: python3.10
      CodeUri: s3://exodblambdafunctions/0f2075876d8daf9a965930aa5b86e734
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud
    Metadata:
      SamResourceId: updateOngoingAttributeFunc
  updateOngoingEventProcessor:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: exodb-eventsUpdateOngoingEventProcessor
      Handler: updateOngoingEventProcessor.handler
      Runtime: python3.10
      CodeUri: s3://exodblambdafunctions/90c4765d484c437d4c0ab94a427600b1
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud
    Metadata:
      SamResourceId: updateOngoingEventProcessor
  updateOngoingEventQueue:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: exodb-eventsUpdateOngoingEventQueue
      Handler: updateOngoingEventQueue.handler
      Runtime: python3.10
      CodeUri: s3://exodblambdafunctions/83c966565043c88db14d73cf6375e000
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud
    Metadata:
      SamResourceId: updateOngoingEventQueue
  updateFutureEventsUrlFinder:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: exodb-eventsFutureUpdateFuncUrlFinder
      Handler: updateFutureEventsUrlFinder.url_finder_handler
      Runtime: python3.10
      CodeUri: s3://exodblambdafunctions/bde111d898f0a2cd563d7ef285d07a97
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud
    Metadata:
      SamResourceId: updateFutureEventsUrlFinder
  websocketConnect:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: exodb-websocketConnectFunction
      Handler: websocketConnect.handler
      Runtime: nodejs20.x
      CodeUri: s3://exodblambdafunctions/ef79b0f323a8624abebb99aa85bd0a28
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud
    Metadata:
      SamResourceId: websocketConnect
  websocketDisconnect:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: exodb-websocketDisconnectFunction
      Handler: websocketDisconnect.handler
      Runtime: nodejs20.x
      CodeUri: s3://exodblambdafunctions/05ed40e38b858223e10065f3f1c0cbf7
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud
    Metadata:
      SamResourceId: websocketDisconnect
