AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A SAM template for deploying multiple Lambda functions.
Resources:
  eventsGet:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: exodb-eventsGetFunc
      Handler: eventsGet.handler
      Runtime: nodejs20.x
      CodeUri: s3://exodblambdafunctions/26c11956b306490d854384d3ecce6530
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud
    Metadata:
      SamResourceId: eventsGet
  eventIdGetPost:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: exodb-eventIdGetPostFunc
      Handler: eventIdGetPost.handler
      Runtime: nodejs20.x
      CodeUri: s3://exodblambdafunctions/b2099d9996aba96e50ba941d45b740c4
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud
    Metadata:
      SamResourceId: eventIdGetPost
  divisionsGet:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: exodb-eventDivisionsGetFunc
      Handler: divisionsGet.handler
      Runtime: nodejs20.x
      CodeUri: s3://exodblambdafunctions/15514f42a88a761df71b41acb835785c
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud
    Metadata:
      SamResourceId: divisionsGet
  divIdGet:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: exodb-eventDivIdGetFunc
      Handler: divIdGet.handler
      Runtime: nodejs20.x
      CodeUri: s3://exodblambdafunctions/fb40d1e6b7f719aa050fecac244ea765
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud
    Metadata:
      SamResourceId: divIdGet
  teamsGet:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: exodb-teamsGetFunc
      Handler: teamsGet.handler
      Runtime: nodejs20.x
      CodeUri: s3://exodblambdafunctions/d7723a59b8168e4134556a43a386ad38
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud
    Metadata:
      SamResourceId: teamsGet
  teamsIdGetPost:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: exodb-teamsIdGetpostFunc
      Handler: teamsIdGetPost.handler
      Runtime: nodejs20.x
      CodeUri: s3://exodblambdafunctions/25bff56087c7bac5f2de6ecf143518c0
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud
    Metadata:
      SamResourceId: teamsIdGetPost
  matchesIdGetPost:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: exodb-matchesIdGetPostFunc
      Handler: matchesIdGetPost.handler
      Runtime: nodejs20.x
      CodeUri: s3://exodblambdafunctions/0ecc7d8360bf467dfb63b93aad9ff065
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud
    Metadata:
      SamResourceId: matchesIdGetPost
  rankingsIdGetPost:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: exodb-rankingsIdGetPostFunc
      Handler: rankingsIdGetPost.handler
      Runtime: nodejs20.x
      CodeUri: s3://exodblambdafunctions/b8df9e34c4fb377ee2623cb7cfa820ad
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud
    Metadata:
      SamResourceId: rankingsIdGetPost
  awardsIdGetPost:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: exodb-awardsIdGetPostFunc
      Handler: awardsIdGetPost.handler
      Runtime: nodejs20.x
      CodeUri: s3://exodblambdafunctions/a6b974321c12f1f05687bf8122cc1249
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud
    Metadata:
      SamResourceId: awardsIdGetPost
  searchGet:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: exodb-searchGetFunc
      Handler: searchGet.handler
      Runtime: nodejs20.x
      CodeUri: s3://exodblambdafunctions/1794a0979943af510f3a62429439944a
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud
    Metadata:
      SamResourceId: searchGet
  skillsIdGetPost:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: exodb-skillsIdGetPostFunc
      Handler: skillsIdGetPost.handler
      Runtime: nodejs20.x
      CodeUri: s3://exodblambdafunctions/1eb7500581c6ec8bf5e55d77dd1ee26d
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud
    Metadata:
      SamResourceId: skillsIdGetPost
  skillsRankingGet:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: exodb-skillsRankingGetFunc
      Handler: skillsRankingGet.handler
      Runtime: nodejs20.x
      CodeUri: s3://exodblambdafunctions/571a65f0d7cc97e833ca731667574c95
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud
    Metadata:
      SamResourceId: skillsRankingGet
  auditOngoing:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: exodb-eventsAuditOngoing
      Handler: auditOngoing.handler
      Runtime: python3.10
      CodeUri: s3://exodblambdafunctions/90808ea0b32500fd98ddde324993b28b
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud
    Metadata:
      SamResourceId: auditOngoing
  updateTeamFromStream:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: exodb-updateTeamFromStream
      Handler: updateTeamFromStream.handler
      Runtime: python3.10
      CodeUri: s3://exodblambdafunctions/a135e4c5bd41492ff67ea7edea1566f4
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud
    Metadata:
      SamResourceId: updateTeamFromStream
  updateFutureEventsDataProcessor:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: exodb-eventsFutureUpdateFuncDataProcessor
      Handler: updateFutureEventsDataProcessor.handler
      Runtime: python3.10
      CodeUri: s3://exodblambdafunctions/f8b3deca2d3c5ff7a28476ca899c44d4
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud
    Metadata:
      SamResourceId: updateFutureEventsDataProcessor
  updateOngoingAttributeFunc:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: exodb-eventsUpdateOngoingAttribute
      Handler: updateOngoingAttribute.handler
      Runtime: python3.10
      CodeUri: s3://exodblambdafunctions/80195a0ba0062d945ba7cfd53a431d7d
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud
    Metadata:
      SamResourceId: updateOngoingAttributeFunc
  updateOngoingEventProcessor:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: exodb-eventsUpdateOngoingEventProcessor
      Handler: updateOngoingEventProcessor.handler
      Runtime: python3.10
      CodeUri: s3://exodblambdafunctions/826c30f7b24208cfd8f35ab2e0937b04
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud
    Metadata:
      SamResourceId: updateOngoingEventProcessor
  updateOngoingEventQueue:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: exodb-eventsUpdateOngoingEventQueue
      Handler: updateOngoingEventQueue.handler
      Runtime: python3.10
      CodeUri: s3://exodblambdafunctions/7e9cae408e9f260e906113bc15b2f952
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud
    Metadata:
      SamResourceId: updateOngoingEventQueue
  updateFutureEventsUrlFinder:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: exodb-eventsFutureUpdateFuncUrlFinder
      Handler: updateFutureEventsUrlFinder.url_finder_handler
      Runtime: python3.10
      CodeUri: s3://exodblambdafunctions/a798d02425a5262a1fa63ae6faac51f6
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud
    Metadata:
      SamResourceId: updateFutureEventsUrlFinder
  updateOpenSearch:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: exodb-updateOpenSearchFunc
      Handler: updateOpenSearch.handler
      Runtime: python3.10
      CodeUri: s3://exodblambdafunctions/0f0071b94a913a1e4593a333d9bb0fff
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud
    Metadata:
      SamResourceId: updateOpenSearch
  auditTeamDataProcessor:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: exodb-auditTeamDataProcessorFunc
      Handler: auditTeamDataProcessor.handler
      Runtime: python3.10
      CodeUri: s3://exodblambdafunctions/086a27ea0d53cb4c9a16d97259233e58
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud
    Metadata:
      SamResourceId: auditTeamDataProcessor
  auditTeamDataQueue:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: exodb-auditTeamDataQueueFunc
      Handler: auditTeamDataQueue.handler
      Runtime: python3.10
      CodeUri: s3://exodblambdafunctions/6ccfde6027dd50283f774894a375d0cb
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud
    Metadata:
      SamResourceId: auditTeamDataQueue
