AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A SAM template for deploying multiple Lambda functions.

Resources:
  # REST Functions

  ## Events
  eventsGet:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-eventsGetFunc
      Handler: eventsGet.handler
      Runtime: nodejs20.x 
      CodeUri: ./restApi/Events/eventsGet/
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud

  ## eventId
  eventIdGetPost:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-eventIdGetPostFunc
      Handler: eventIdGetPost.handler
      Runtime: nodejs20.x 
      CodeUri: ./restApi/Events/eventId/eventIdGetPost/
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud

  ## divisions
  divisionsGet:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-eventDivisionsGetFunc
      Handler: divisionsGet.handler
      Runtime: nodejs20.x 
      CodeUri: ./restApi/Events/eventId/divisions/divisionsGet
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud

  ## divId
  divIdGet:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-eventDivIdGetFunc
      Handler: divIdGet.handler
      Runtime: nodejs20.x 
      CodeUri: ./restApi/Events/eventId/divisions/divId/divIdGet
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud

  # Teams
  teamsGet:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-teamsGetFunc
      Handler: teamsGet.handler
      Runtime: nodejs20.x 
      CodeUri: ./restApi/Teams/teamsGet
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud

  teamsIdGetPost:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-teamsIdGetpostFunc
      Handler: teamsIdGetPost.handler
      Runtime: nodejs20.x 
      CodeUri: ./restApi/Teams/teamsId/teamsIdGetPost
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud

  # Matches
  matchesIdGetPost:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-matchesIdGetPostFunc
      Handler: matchesIdGetPost.handler
      Runtime: nodejs20.x 
      CodeUri: ./restApi/Matches/matchesId/matchesIdGetPost
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud

  # Rankings
  rankingsIdGetPost:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-rankingsIdGetPostFunc
      Handler: rankingsIdGetPost.handler
      Runtime: nodejs20.x 
      CodeUri: ./restApi/Rankings/rankingsId/rankingsIdGetPost
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud

  # Awards
  awardsIdGetPost:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-awardsIdGetPostFunc
      Handler: awardsIdGetPost.handler
      Runtime: nodejs20.x 
      CodeUri: ./restApi/Awards/awardsId/awardsIdGetPost
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud
    
  # Search
  searchGet:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-searchGetFunc
      Handler: searchGet.handler
      Runtime: nodejs20.x 
      CodeUri: ./restApi/Search/searchGet
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud

  # Skills
  skillsIdGetPost:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-skillsIdGetPostFunc
      Handler: skillsIdGetPost.handler
      Runtime: nodejs20.x 
      CodeUri: ./restApi/Skills/skillsId/skillsIdGetPost
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud

  # SkillsRanking
  skillsRankingGet:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-skillsRankingGetFunc
      Handler: skillsRankingGet.handler
      Runtime: nodejs20.x 
      CodeUri: ./restApi/SkillsRanking/skillsRankingGet
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud

  # EloRankings
  eloRankingsGet:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-eloRankingsGet
      Handler: eloRankingsGet.handler
      Runtime: nodejs20.x 
      CodeUri: ./restApi/EloRankings/eloRankingsGet
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud

  # TsRankings
  tsRankingsGet:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-tsRankingsGet
      Handler: tsRankingsGet.handler
      Runtime: nodejs20.x 
      CodeUri: ./restApi/TsRankings/tsRankingsGet
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud

  # LastPageIdGet
  lastPageIdGet:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-lastPageIdGet
      Handler: lastPageIdGet.handler
      Runtime: nodejs20.x 
      CodeUri: ./restApi/LastPage/lastPageId/lastPageIdGet
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud

  # Other Functions

  auditOngoing:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-eventsAuditOngoing
      Handler: auditOngoing.handler
      Runtime: python3.10 
      CodeUri: ./otherFuncs/auditOngoing
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud

  updateTeamFromStream:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-updateTeamFromStream
      Handler: updateTeamFromStream.handler
      Runtime: python3.10 
      CodeUri: ./otherFuncs/updateTeamFromStream
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud

  updateFutureEventsDataProcessor:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-eventsFutureUpdateFuncDataProcessor
      Handler: updateFutureEventsDataProcessor.handler
      Runtime: python3.10 
      CodeUri: ./otherFuncs/updateFutureEvents/updateFutureEventsDataProcessor
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud

  updateOngoingAttributeFunc:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-eventsUpdateOngoingAttribute
      Handler: updateOngoingAttribute.handler
      Runtime: python3.10 
      CodeUri: ./otherFuncs/updateOngoingAttribute
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud
  
  updateOngoingEventProcessor:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-eventsUpdateOngoingEventProcessor
      Handler: updateOngoingEventProcessor.handler
      Runtime: python3.10 
      CodeUri: ./otherFuncs/updateOngoingEvent/updateOngoingEventProcessor
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud

  updateOngoingEventQueue:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-eventsUpdateOngoingEventQueue
      Handler: updateOngoingEventQueue.handler
      Runtime: python3.10 
      CodeUri: ./otherFuncs/updateOngoingEvent/updateOngoingEventQueue
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud

  updateOngoingLeagueQueue:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-eventsUpdateOngoingLeagueQueue
      Handler: updateOngoingLeagueQueue.handler
      Runtime: python3.10 
      CodeUri: ./otherFuncs/updateOngoingEvent/updateOngoingLeagueQueue
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud
  
  updateFutureEventsUrlFinder:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-eventsFutureUpdateFuncUrlFinder
      Handler: updateFutureEventsUrlFinder.url_finder_handler
      Runtime: python3.10 
      CodeUri: ./otherFuncs/updateFutureEvents/updateFutureEventsUrlFinder
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud
  
  updateOpenSearch:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-updateOpenSearchFunc
      Handler: updateOpenSearch.handler
      Runtime: python3.10 
      CodeUri: ./otherFuncs/updateOpenSearch/
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud

  auditTeamDataProcessor:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-auditTeamDataProcessorFunc
      Handler: auditTeamDataProcessor.handler
      Runtime: python3.10 
      CodeUri: ./otherFuncs/auditTeamData/auditTeamDataProcessor/
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud

  auditTeamDataQueue:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-auditTeamDataQueueFunc
      Handler: auditTeamDataQueue.handler
      Runtime: python3.10 
      CodeUri: ./otherFuncs/auditTeamData/auditTeamDataQueue/
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud

  calculateEloRankings:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-calculateEloRankingsFunc
      Handler: calculateEloRankings.handler
      Runtime: python3.10 
      CodeUri: ./otherFuncs/calculateRankings/calculateEloRankings/
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud
  
  calculateTsRankings:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-calculateTsRankingsFunc
      Handler: calculateTsRankings.handler
      Runtime: python3.10 
      CodeUri: ./otherFuncs/calculateRankings/calculateTsRankings/
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud

  calculateSkillsRankings:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-calculateSkillsRankingsFunc
      Handler: calculateSkillsRankings.handler
      Runtime: python3.10 
      CodeUri: ./otherFuncs/calculateRankings/calculateSkillsRankings/
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud
  
  updateReveals:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-updateReveals
      Handler: updateReveals.handler
      Runtime: python3.10 
      CodeUri: ./otherFuncs/updateReveals/
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud
      