AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A SAM template for deploying multiple Lambda functions.

Resources:
  # REST Functions
  eventsGet:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-eventsGetFunc
      Handler: eventsGet.handler
      Runtime: nodejs20.x 
      CodeUri: ./restApi/Events/eventsGet/
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud


  # Other Functions

  updateFutureEventsDataProcessor:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-eventsFutureUpdateFuncDataProcessor
      Handler: updateFutureEventsDataProcessor.handler
      Runtime: python3.10 
      CodeUri: ./otherFuncs/updateFutureEvents/updateFutureEventsDataProcessor
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud
  
  updateFutureEventsUrlFinder:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-eventsFutureUpdateFuncUrlFinder
      Handler: updateFutureEventsUrlFinder.url_finder_handler
      Runtime: python3.10 
      CodeUri: ./otherFuncs/updateFutureEvents/updateFutureEventsUrlFinder
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud

  # Websocket Functions
  websocketConnect:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-websocketConnectFunction
      Handler: websocketConnect.handler
      Runtime: nodejs20.x 
      CodeUri: ./websocketApi/websocketConnect/
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud

  websocketDisconnect:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-websocketDisconnectFunction 
      Handler: websocketDisconnect.handler
      Runtime: nodejs20.x
      CodeUri: ./websocketApi/websocketDisconnect/
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud
      