AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A SAM template for deploying multiple Lambda functions.

Resources:
  # REST Functions

  ## Events
  eventsGet:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-eventsGetFunc
      Handler: eventsGet.handler
      Runtime: nodejs20.x 
      CodeUri: ./restApi/Events/eventsGet/
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud

  ## eventId
  eventIdGetPost:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-eventIdGetPostFunc
      Handler: eventIdGetPost.handler
      Runtime: nodejs20.x 
      CodeUri: ./restApi/Events/eventId/eventIdGetPost/
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud

  ## divisions
  divisionsGet:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-eventDivisionsGetFunc
      Handler: divisionsGet.handler
      Runtime: nodejs20.x 
      CodeUri: ./restApi/Events/eventId/divisions/divisionsGet
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud

  ## divId
  divIdGet:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-eventDivIdGetFunc
      Handler: divIdGet.handler
      Runtime: nodejs20.x 
      CodeUri: ./restApi/Events/eventId/divisions/divId/divIdGet
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud

  # Teams

  teamsIdGetPost:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-teamsIdGetpostFunc
      Handler: teamsIdGetPost.handler
      Runtime: nodejs20.x 
      CodeUri: ./restApi/Teams/teamsId/teamsIdGetPost
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud

  # Other Functions

  auditOngoing:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-eventsAuditOngoing
      Handler: auditOngoing.handler
      Runtime: python3.10 
      CodeUri: ./otherFuncs/auditOngoing
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud

  updateTeamFromStream:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-updateTeamFromStream
      Handler: updateTeamFromStream.handler
      Runtime: python3.10 
      CodeUri: ./otherFuncs/updateTeamFromStream
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud

  updateFutureEventsDataProcessor:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-eventsFutureUpdateFuncDataProcessor
      Handler: updateFutureEventsDataProcessor.handler
      Runtime: python3.10 
      CodeUri: ./otherFuncs/updateFutureEvents/updateFutureEventsDataProcessor
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud

  updateOngoingAttributeFunc:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-eventsUpdateOngoingAttribute
      Handler: updateOngoingAttribute.handler
      Runtime: python3.10 
      CodeUri: ./otherFuncs/updateOngoingAttribute
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud
  
  updateOngoingEventProcessor:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-eventsUpdateOngoingEventProcessor
      Handler: updateOngoingEventProcessor.handler
      Runtime: python3.10 
      CodeUri: ./otherFuncs/updateOngoingEvent/updateOngoingEventProcessor
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud

  updateOngoingEventQueue:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-eventsUpdateOngoingEventQueue
      Handler: updateOngoingEventQueue.handler
      Runtime: python3.10 
      CodeUri: ./otherFuncs/updateOngoingEvent/updateOngoingEventQueue
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud
  
  updateFutureEventsUrlFinder:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-eventsFutureUpdateFuncUrlFinder
      Handler: updateFutureEventsUrlFinder.url_finder_handler
      Runtime: python3.10 
      CodeUri: ./otherFuncs/updateFutureEvents/updateFutureEventsUrlFinder
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud
      