AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A SAM template for deploying multiple Lambda functions.

Resources:

  nMostRecent:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-nMostRecentFunc
      Handler: nMostRecent.handler
      Runtime: nodejs20.x 
      CodeUri: ./nMostRecent/
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud

  ongoingEvents:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-ongoingEventsFunc
      Handler: ongoingEvents.handler
      Runtime: nodejs20.x 
      CodeUri: ./ongoingEvents/
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud

  websocketConnect:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-websocketConnectFunction
      Handler: websocketConnect.handler
      Runtime: nodejs20.x 
      CodeUri: ./websocketConnect/
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud

  websocketDisconnect:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-websocketDisconnectFunction 
      Handler: websocketDisconnect.handler
      Runtime: nodejs20.x
      CodeUri: ./websocketDisconnect/
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud

  ongoingStream:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: exodb-ongoingStreamFunc
      Handler: ongoingStream.handler
      Runtime: nodejs20.x 
      CodeUri: ./ongoingStream/
      Role: arn:aws:iam::228049799584:role/service-role/dynamoDB_crud